# Generated by Django 6.0.2 on 2026-02-04 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elements', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date_posted', models.DateField(auto_now_add=True)),
                ('element', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='elements.element')),
            ],
        ),
    ]
