# Generated by Django 6.0.2 on 2026-02-20 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('nit', models.PositiveBigIntegerField(default=0, unique=True)),
                ('adress', models.CharField(max_length=255)),
            ],
        ),
    ]
